### ISSUE TITLE
Changing API key makes previous one unusable, and can't mark as received

### ISSUE THREAD

**Issue by Onizuka89** [nightzirch/secret-toymaker.backend#18]
Probably I am the only one who have managed to fuck up like this, but used an alt account's API key rather than main, later changed it. After I realized that my secret toymaker sent me a gift, I realized I couldn't mark it as received, since the current key isn't in the gifting pool of course, so tried to change it back, but it just freeze, so can't get the fields and press the button to mark as received

**Comment by Onizuka89** [comment]
Seemed just to take some time to fix itself, my bad.

**Comment by nightzirch** [comment]
I'm glad it worked itself out. This is an interesting issue and I still gotta make sure changing API key to a different account won't crash things.

We use the unique ID of the Arenanet account (since the account name – e.g. account.1234 – may in very rare cases change) when adding participants. This is to avoid people signing up with multiple emails but the same game account.

If you changed the API to a different account after being matched, the gift's giftee property will reference the old game account, which again will reference your correct user profile with your correct email. So in theory, it should be fine.

As you experienced, the only bad thing here is that you received the item on your old account. The delay may be caused by other things.

Does that sound about right? Did you experience any other downsides?
